lane :ios_release do
  api_key = app_store_connect_api_key(
    is_key_content_base64: true
  )  
  upload_to_testflight(
    ipa: "build/polaris.ipa",
    skip_submission: true,
    skip_waiting_for_build_processing: true
  )
end
