name: ci

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@5.4.0
        with:
          expo-version: 3.x
          expo-cache: true

      - name: Cache dependencies
        uses: actions/cache@v2.1.5
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}

      - name: Cache Cypress binary
        uses: actions/cache@v2.1.5
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-cypress-${{ hashFiles('**/package.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-cypress-

      - run: yarn
      - run: yarn lint
      - run: yarn prestorybook
      - run: yarn test:ci
      - run: yarn web:ci
      - run: yarn e2e:web:run:ci

  build:
    needs: test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@5.4.0
        with:
          expo-version: 3.x
          expo-cache: true

      - name: Cache dependencies
        uses: actions/cache@v2.1.5
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}

      - run: yarn
      - run: yarn prestorybook
      # ios and android js bundles + assets
      - run: expo export -f --dev --public-url http://localhost
      # web js bundle + assets
      - run: expo build:web
