name: e2e android tests

# TODO: change this to only run on master pushes
on:
  # pull_request:
  workflow_dispatch:
    inputs:
      artifact-run-id:
        description: 'Run id from which to get earlier artifacts, instead of generating new ones'

jobs:
  build:
    if: ${{ !github.event.inputs.artifact-run-id }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: actions/cache@v2
        with:
          path: ~/.turtle
          key: ${{ runner.os }}-turtle
          restore-keys: |
            ${{ runner.os }}-turtle
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: '8'
      - uses: expo/expo-github-action@v5
        with:
          expo-cache: true
          expo-token: ${{ secrets.EXPO_TOKEN }}
      - run: yarn
      - run: expo doctor
      - run: expo diagnostics
      # TODO: what about a server when the app is running on a device?
      - run: expo export --clear --force --dev --public-url http://localhost:5000 --output-dir dist
      - run: npx serve dist &
      - run: |
          echo "$EXPO_ANDROID_KEYSTORE_BASE64" > keystore.jks.base64
          base64 --decode keystore.jks.base64 > keystore.jks
          yarn build:local:android -- --public-url http://localhost:5000/android-index.json --allow-non-https-public-url --keystore-path ./keystore.jks --keystore-alias $EXPO_ANDROID_KEYSTORE_ALIAS
        env:
          EXPO_ANDROID_KEYSTORE_BASE64: ${{ secrets.EXPO_ANDROID_KEYSTORE_BASE64 }}
          EXPO_ANDROID_KEYSTORE_ALIAS: ${{ secrets.EXPO_ANDROID_KEYSTORE_ALIAS }}
          EXPO_ANDROID_KEYSTORE_PASSWORD: ${{ secrets.EXPO_ANDROID_KEYSTORE_PASSWORD }}
          EXPO_ANDROID_KEY_PASSWORD: ${{ secrets.EXPO_ANDROID_KEY_PASSWORD }}
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/

  e2e:
    needs: build
    if: always()
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Download artifact from run ${{ github.event.inputs.artifact-run-id }}
        uses: dawidd6/action-download-artifact@v2
        if: ${{ github.event.inputs.artifact-run-id }}
        with:
          workflow: ${{ github.workflow }}
          name: build
          path: build
          run_id: ${{ github.event.inputs.artifact-run-id }}
      - uses: actions/download-artifact@v2
        if: ${{ !github.event.inputs.artifact-run-id }}
        with:
          name: build
          path: build
      - run: yarn
        working-directory: e2e
      - run: npx appium-doctor --android
      - run: npx appium &
      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          working-directory: e2e
          script: yarn e2e:android:run
