name: e2e android tests

# TODO: change this to only run on master pushes
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/cache@v2
        with:
        path: ~/.turtle
        key: ${{ runner.os }}-turtle
        restore-keys: |
          ${{ runner.os }}-turtle
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: '8'
      - uses: expo/expo-github-action@v5
        with:
          expo-packager: npm
          expo-cache: true
          expo-token: ${{ secrets.EXPO_TOKEN }}
      - run: npm i
      - run: expo doctor
      - run: expo diagnostics
      # TODO: what about a server when the app is running on a device?
      - run: expo export --dev --public-url http://localhost:5000
      # TODO: check if running the server is needed to do the build
      - run: npx serve dist &
      - run: |
          echo "$EXPO_ANDROID_KEYSTORE_BASE64" > keystore.jks.base64
          base64 --decode keystore.jks.base64 > keystore.jks
          npm run build:local:android -- --public-url http://localhost:5000/android-index.json --allow-non-https-public-url --keystore-path ./keystore.jks --keystore-alias $EXPO_ANDROID_KEYSTORE_ALIAS
        env:
          EXPO_ANDROID_KEYSTORE_BASE64: ${{ secrets.EXPO_ANDROID_KEYSTORE_BASE64 }}
          EXPO_ANDROID_KEYSTORE_ALIAS: ${{ secrets.EXPO_ANDROID_KEYSTORE_ALIAS }}
          EXPO_ANDROID_KEYSTORE_PASSWORD: ${{ secrets.EXPO_ANDROID_KEYSTORE_PASSWORD }}
          EXPO_ANDROID_KEY_PASSWORD: ${{ secrets.EXPO_ANDROID_KEY_PASSWORD }}
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/

  e2e:
    needs: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      # TODO: this action can be useful to download from another build in case we want to split this into multiple workflows
      # - uses: dawidd6/action-download-artifact@v2
      - uses: actions/download-artifact@v2
        with:
          # (inputs for the other action)
          # workflow: e2e.android.yml
          # run_id: 669563691
          name: build
          path: build
      - run: npm i
        working-directory: e2e
      - run: npx appium-doctor --android
      - run: npx appium &
      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          working-directory: e2e
          script: npm run e2e:android:run

  upload:
    if: false
    needs: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      # TODO: this action can be useful to download from another build in case we want to split this into multiple workflows
      # - uses: dawidd6/action-download-artifact@v2
      - uses: actions/download-artifact@v2
        with:
          # (inputs for the other action)
          workflow: e2e.android.yml
          run_id: 669563691
          name: build
          path: build
      - uses: expo/expo-github-action@v5
        with:
          expo-packager: npm
          expo-cache: true
          expo-token: ${{ secrets.EXPO_TOKEN }}
